-- db/scripts/create_tables.sql

CREATE TABLE exercise_logs (
  id SERIAL PRIMARY KEY,
  date DATE NOT NULL,
  description VARCHAR(255) NOT NULL,
  duration INTERVAL NOT NULL,
  distance DOUBLE PRECISION NOT NULL,
  pace DOUBLE PRECISION NOT NULL,
  zone5 DOUBLE PRECISION NOT NULL,
  zone4 DOUBLE PRECISION NOT NULL,
  zone3 DOUBLE PRECISION NOT NULL,
  zone2 DOUBLE PRECISION NOT NULL,
  zone1 DOUBLE PRECISION NOT NULL,
  avg_hr INTEGER NOT NULL,
  max_hr INTEGER NOT NULL,
  strain DOUBLE PRECISION NOT NULL
);

CREATE TABLE exercise_averages (
  id SERIAL PRIMARY KEY,
  duration_avg INTERVAL NOT NULL,
  distance_avg DOUBLE PRECISION NOT NULL,
  pace_avg DOUBLE PRECISION NOT NULL,
  zone5_avg DOUBLE PRECISION NOT NULL,
  zone4_avg DOUBLE PRECISION NOT NULL,
  zone3_avg DOUBLE PRECISION NOT NULL,
  zone2_avg DOUBLE PRECISION NOT NULL,
  zone1_avg DOUBLE PRECISION NOT NULL,
  avg_hr_avg DOUBLE PRECISION NOT NULL,
  max_hr_avg DOUBLE PRECISION NOT NULL,
  strain_avg DOUBLE PRECISION NOT NULL
);